name: CivCraft
main: com.avrgaming.civcraft.main.CivCraft
softdepends: [dynmap, HolographicDisplays, NametagEdit, TitleAPI, VanishNoPacket, WorldBorder]
author: YourCoal
version: 1.9.4

commands:
    cmat:
        aliases:
    backpack:
        aliases:
    test:
        aliases:
    town:
        aliases: [t]
    plot:
        aliases: [p]
    resident:
        aliases: [res]
    dbg:
        aliases:
    accept:
        aliases:
    deny:
        aliases:
    civ:
        aliases: [c]
    tc:
        aliases:
    cc:
        aliases:
    ad:
        aliases:
    mod:
        aliases:
    build:
        aliases:
    market:
        aliases:
    select:
        aliases:
    econ:
        aliases: [money]
    pay:
        aliases:
    here:
        aliases:
    camp:
        aliases:
    report:
        aliases:
    vote:
        aliases: [v]
    kill:
        aliases:
